version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.5.7
    container_name: ollama_container
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    

    # Configuration  GPU NVIDIA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  

  qdrant:
    image: qdrant/qdrant:v1.12.0
    container_name: qdrant_container
    restart: unless-stopped
    ports:
      - "6333:6333" #-- Api/Dashboard
      - "6334:6334" #-- Api gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
      - ./qdrant_init:/qdrant_init_data:ro

  backend:
    build: .
    dockerfile: Dockerfile
    container_name: symfony_php
    restart: unless-stopped
    volumes: 
      - ../../../:/var/www/html
    env_file:
      - ../../../.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mariadb
    
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../../../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend

  mariadb: 
    image: mariadb:10.11.6
    container_name: symfony_mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ../../../.env

  
volumes:
  ollama_storage:
  qdrant_storage:
  mariadb_data:

networks:
  default:
    name: Hiring_FORGE_NETWORK
    external: true