@startuml Usecase

left to right direction

actor "User" as User
actor Candidate


rectangle "Actions" {
    (Consulter les offres d'emploi) as ConslutJobOfferList
    (Consulter une offre d'emploi) as ConsultJobOffer
    (Filtrer les offres) as FilterJobOffer

    (Consulter des candidatures) as ConsultCandidateList
    (Consulter une candidature) as ConsultCandidate
    (Filtrer les candidatures) as FilterCandidate

    (Gérer le profil) as ManageCandidateProfil
    (Importer CV) as ImportCV
    usecase "Modification d'information (nom)" as ModifyCandidateName 
    usecase "Modification de l'addrèsse" as ModifyAddress 


    (Gérer le profil) as ManageUserProfil
    (Téléversement d'une video de presentation) as UploadVideo
    (Modification Siret) as ChangeSiretNumber
    (Modification des credentials) as ChangeAuthCredential

    (CV Importé) as ImportedCV
    (Postuler à une offre d'emploi) as ApplyJobOffer
    

    (Gérer les candidatures) as ManageCandidates
    (Selection des candidats) as CandidateSelection
    (Planification d'entretien) as PlanInterview
    (Mise en place d'evaluation technique) as EvalCandidate 


    (Gérer les offres d'emplois) as ManageJobOffer
    (Publication d'une offre) as PublishJobOffer

    (Supprimer une offre d'emploi) as DeleteJobOffer

    (Gérer des agents techniques) as ManageAgent
    (Générer des des agents techniques) as CreateAgent
    (Definission du scope d'un agent) as AgentScopeAction
    (Supprimer un agent) as DeleteAgent 
}


'Basics Actions
ConslutJobOfferList ..> ConsultJobOffer: extends
ConslutJobOfferList ..> FilterJobOffer: extends

User --> ConslutJobOfferList
User --> ChangeAuthCredential
Candidate --> ChangeAuthCredential
Candidate -> ConslutJobOfferList


' CandidatesProfil
ManageCandidateProfil ..> ModifyCandidateName : extends
ManageCandidateProfil ..> ModifyAddress :extends
ManageCandidateProfil ..> ImportCV : extends

Candidate --> ManageCandidateProfil

' User  Applications (Apply)
Candidate --> ApplyJobOffer
ApplyJobOffer <.up. ImportedCV : include 

' Manage Agent
ManageAgent ..> CreateAgent : etends
ManageAgent ..> AgentScopeAction : extends
ManageAgent ..> DeleteAgent : extends

User -> ManageAgent

'Manage Candidate
ConsultCandidateList ..> ConsultCandidate : extends
ConsultCandidateList ..> FilterCandidate : extends

ManageCandidates ..> CandidateSelection : extends
ManageCandidates ..> PlanInterview : extends
ManageCandidates ..> EvalCandidate : extends

User -> ManageCandidates
User -> ConsultCandidateList

'Manage User profil
ManageUserProfil ..> ModifyCandidateName: extends
ManageUserProfil ..> ModifyAddress     : extends
ManageUserProfil ..> UploadVideo       : extends
ManageUserProfil ..> ChangeSiretNumber : extends

User -> ManageUserProfil

' Manage Offers
ManageJobOffer ..> PublishJobOffer : extends
ManageJobOffer ..> DeleteJobOffer  : extends
User -> ManageJobOffer




@enduml