@startuml Usecase

left to right direction

actor "User" as User
actor Candidate
actor Agent
actor "HR Director" as HRDirector

rectangle "Actions" {


    (Consulter les offres d'emploi) as ConslutJobOfferList
    (Consulter une offre d'emploi) as ConsultJobOffer
    (Filtrer les offres) as FilterJobOffer

    (Consulter des candidatures) as ConsultCandidateList
    (Consulter une candidature) as ConsultCandidate
    (Filtrer les candidatures) as FilterCandidate

    (Gérer le profil) as ManageCandidateProfil
    (Importer CV) as ImportCV
    usecase "Modification d'information (nom)" as ModifyCandidateName 
    usecase "Modification de l'addrèsse" as ModifyAddress 

    (Gérer le profil) as ManageUserProfil
    (Téléversement d'une video de presentation) as UploadVideo
    (Modification Siret) as ChangeSiretNumber
    (Modification des credentials) as ChangeAuthCredential

    (CV Importé) as ImportedCV
    (Postuler à une offre d'emploi) as ApplyJobOffer

    (Gérer les candidatures) as ManageCandidates
    (Selection des candidats) as CandidateSelection
    (Planification d'entretien) as PlanInterview

    (Gérer les offres d'emplois) as ManageJobOffer
    (Publication d'une offre) as PublishJobOffer
    (Créer une offre d'emploi) as CreateOffer
    (Redéfinir en tant que brouillon) as DraftOffer
    (Supprimer une offre d'emploi) as DeleteJobOffer
    (Modifier d'emploi) as ModifyOffer

    (Gérer des agents techniques) as ManageAgent
    (Générer des des agents techniques) as CreateAgent
    (Definission du scope d'un agent) as AgentScopeAction
    (Assigner une tâche) as AgentAssignement
    (Supprimer un agent) as DeleteAgent 




    (Accéder au système) as AccessSystem
    (Consulter le dashboard global) as ViewDashboard
    (Consulter les recruteurs) as GetRecruiters
    (Consulter les offres par recruteur) as GetOffersByRecruiter
    (Consulter les candidatures globales) as GetApplications
    (Calculer les KPI) as ComputeKPIs
    (Modification des credentials) as ChangeAuthCredential2

}



ConslutJobOfferList ..> ConsultJobOffer: extends
ConslutJobOfferList ..> FilterJobOffer: extends

User --> ConslutJobOfferList
User --> ChangeAuthCredential
Candidate --> ChangeAuthCredential
Candidate -> ConslutJobOfferList

ManageCandidateProfil ..> ModifyCandidateName : extends
ManageCandidateProfil ..> ModifyAddress :extends
ManageCandidateProfil ..> ImportCV : extends

Candidate --> ManageCandidateProfil

Candidate --> ApplyJobOffer
ApplyJobOffer <.up. ImportedCV : include 

ManageAgent ..> CreateAgent : extends
ManageAgent ..> AgentScopeAction : extends
ManageAgent ..> DeleteAgent : extends
ManageAgent ..> AgentAssignement

User -> ManageAgent

ConsultCandidateList ..> ConsultCandidate : extends
ConsultCandidateList ..> FilterCandidate : extends

ManageCandidates ..> CandidateSelection : extends
ManageCandidates ..> PlanInterview : extends

User -> ManageCandidates
User -> ConsultCandidateList

ManageUserProfil ..> ModifyCandidateName: extends
ManageUserProfil ..> ModifyAddress     : extends
ManageUserProfil ..> UploadVideo       : extends
ManageUserProfil ..> ChangeSiretNumber : extends

User -> ManageUserProfil

ManageJobOffer ..> PublishJobOffer : extends
ManageJobOffer ..> DeleteJobOffer  : extends
ManageJobOffer ..> CreateOffer     : extends
ManageJobOffer ..> ModifyOffer     : extends
ManageJobOffer ..> DraftOffer : extends

User -> ManageJobOffer

Agent ..> ManageJobOffer : extends
Agent ..> ManageCandidates: extends




HRDirector --> AccessSystem
AccessSystem ..> ViewDashboard : extends

ViewDashboard ..> GetRecruiters : extends
ViewDashboard ..> GetOffersByRecruiter : extends
ViewDashboard ..> GetApplications : extends
ViewDashboard ..> ComputeKPIs : extends

HRDirector -down-> ChangeAuthCredential2

@enduml