security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/api/(_profiler|_wdt|assets|build)/
            security: false

        # LOGIN 
        login:
            pattern: ^/api/(candidate|agent|user)/login$
            stateless: true
            custom_authenticators:
                - App\Api\Security\LoginAuthenticatorController

        # API SECURISE 
        api:
            pattern: ^/api/(candidates|agents|users)
            stateless: true
            user_checker: App\Api\Security\AccountChecker
            custom_authenticators:
                - App\Api\Security\JwtAuthenticatorController

        main:
            lazy: true
            provider: users_in_memory

    # contrôle d'accès
    access_control:
        # -- ROUTES PUBLIQUES
        - { path: ^/api/(candidate|agent|user)/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/(candidate|agent|user)/otp,      roles: PUBLIC_ACCESS }

        # -- ROUTES PRIVEES 
        - { path: ^/api/candidates, roles: ROLE_CANDIDATE }
        - { path: ^/api/agents,     roles: ROLE_AGENT }
        - { path: ^/api/users,      roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
