<?php


namespace App\Api\Controllers\Offer;

use App\Api\Responder\ApiResponse;
use App\Application\DTO\Auth\AuthenticatedPerson;
use App\Domain\Offer\OfferRepositoryInterface;

use Psr\Log\LoggerInterface;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;


#[Route('/offers/user')]
class UserOffersController extends AbstractController
{
    public function __construct(
        LoggerInterface $logger,
        private OfferRepositoryInterface $offerRepository
    ){
        ApiResponse::init($logger);
    }


    /**
     * Route /offers/user/jobs/{jobId}?limit=number&skip=number&companyId=number
     */
    #[Route('/jobs/{jobId}', methods: ['GET'])]
    public function getOfferForUser(string $jobId, Request $request): JsonResponse
    {
        try {
                /** @var AuthenticatedPerson|null $user */
                $user = $this->getUser();

                if (!$user) {
                    return ApiResponse::error(
                        message: 'Unauthorized action',
                        statusCode: Response::HTTP_UNAUTHORIZED
                    )->toJsonResponse();
                }

                // retrieving Query Parameters
                $jobId = $request->query->get('jobId'); // Nullable
                $limit = max(1, $request->query->getInt('limit', 17));
                $skip = max(0, $request->query->getInt('skip', 0));
                $companyId = $request->query->get("companyId", null);

                $scheme = [
                    'id' => true,
                    'title' => true,
                    'status' => true,
                    'sentAt' => true,
                    'expiredAt' => true,
                    'salary' => true,
                    'candidate' => [
                        'id' => true,
                        'firstName' => true,
                        'lastName' => true,
                        'email' => true,
                        'image' => [
                            'name' => true,
                            'mime' => true
                        ]
                    ],
                    'application' =>[
                        'id' => true,
                    ],
                    'jobOffer'=>[
                        'id'=>true,
                        'title' => true
                    ]
                ];

                // Call with companyId (returns all offers generated by users from this company)
                $result = $this->offerRepository->fetchOfferProjection(
                    userId: null,
                    companyId: $companyId,
                    jobId: $jobId,
                    scheme: $scheme,
                    limit: $limit,
                    skip: $skip
                );

                return ApiResponse::success(
                    data: $result,
                    message: 'Everything is OK'
                )->toJsonResponse();

            }
            catch (\Throwable $error) {
                return ApiResponse::error(
                    message: 'Something wrong happened',
                    statusCode: Response::HTTP_INTERNAL_SERVER_ERROR
                )->toJsonResponse();
            }
    }


    public function createOffer(){
        try{

        }
        catch(\Exception $error){
            return ApiResponse::error(
                message: 'Something went wrong'
            )->toJsonResponse();
        }
    }

}
