# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration


#--------------------
#   Parameters
#------------------------------
parameters:
    #-------Root Dir
    uploads_base_directory: '%kernel.project_dir%/public/uploads'


#---------------------
#   Services
#------------------------------

services:
    #---------------------
    #  Main Config
    #-----------------------------

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #--------------------------------------
    # API Services (Controller)
    #-------------------------------------
    App\Api\Controllers\:
        resource: '../src/Api/Controllers'
        tags: ['controller.service_arguments']

    #----------------------------
    #   Domain (Composition Root/Bootstrap)
    #--------------------------------
    
    #-----------
    #   Repositories
    #-----------------------

    #------ User ------
    App\Domain\User\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\ORM\User\Repositories\UserRepository
    
    App\Application\Query\Handlers\User\UserQueryRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\ORM\User\Repositories\UserQueryRepository

    #------ Candidate ----
    App\Domain\Candidate\CandidateRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\ORM\Candidate\CandidateRepository

    #----- JobOffer ------
    App\Domain\JobOffer\JobOfferRepositioryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\ORM\JobOffer\Repositories\JobOfferRepository
    
    App\Application\Query\JobOffer\JobOfferQueryRepositoryInterace:
        alias: App\Infrastructure\Persistence\Doctrine\ORM\JobOffer\Repositories\JobOfferQueryRepository
    
    #------ Email -------
    App\Domain\Email\EmailRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\ORM\Email\EmailRepository
    
    #------ OTP -------

    App\Domain\OTP\OTPRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\ORM\Security\Tokens\OTPRepository

    #--------------
    # FileStorage Services
    #-------------------------------
    App\Infrastructure\Storage\FileStorage\MediaStorage:
        arguments:
            $baseStoragePath: '%uploads_base_directory%'

    App\Domain\File\MediaStorageInterface:
        alias: App\Infrastructure\Storage\FileStorage\MediaStorage
    
    App\Domain\File\MediaFactoryInterface:
        alias: App\Infrastructure\Storage\FileStorage\MediaFactory


    #--------------
    # Email Services
    #-------------------------------
    
    App\Domain\Email\EmailServicesInterface:
        alias: App\Infrastructure\Email\EmailServices

    #-------------------------------
    #   Security
    #-------------------------------

    App\Domain\Shared\PasswordHasherInterface:
        alias: App\Infrastructure\Security\PasswordHasher


    #------------------
    #   Dev Packages
    #---------------------------
    monolog.formatter.console:
        class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
    
    