<?php

namespace App\Domain\Notification;


enum NotificationType: string
{
    case JOB_APPLIED = 'JOB_APPLIED';
    case JOB_APPLICATIONS_STATUS_SHIFT = 'JOB_APPLICATIONS_STATUS_SHIFT';

    //-- Application
    case CANDIDATE_REJECTED = 'CANDIDATE_REJECTED';

    //-- Employment
    case EMPLOYMENT_OFFER_GENERATED = "EMPLOYMENT_OFFER_GENERATED";
    case EMPLOYMENT_OFFER_CANCELLED  = "EMPLOYMENT_OFFER_CANCELLED";
    
    //-- Interviews
    case INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED';
    case INTERVIEW_CANCELLED = 'INTERVIEW_CANCELLED';
    case INTERVIEW_ACCEPTED = 'INTERVIEW_ACCEPTED';
    case INTERVIEW_REFUSED = 'INTERVIEW_REFUSED';
    
    //--   HYBRID/GENERAL
    case SYSTEM_ALERT = 'SYSTEM_ALERT';
}