<?php

namespace App\Domain\Notification;


enum NotificationType: string
{
    case JOB_APPLIED = 'JOB_APPLIED';
    case JOB_APPLICATIONS_STATUS_SHIFT = 'JOB_APPLICATIONS_STATUS_SHIFT';

    //-- Employment
    case EMPLOYMENT_OFFER_GENERATED = "EMPLOYMENT_OFFER_GENERATED";
    case EMPLOYMENT_OFFER_CANCELLED  = "EMPLOYMENT_OFFER_CANCELLED";
    

    //-- Interviews
    case INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED';
    case CANDIDATE_REJECTED = 'CANDIDATE_REJECTED';
    
    //--   HYBRID/GENERAL
    case SYSTEM_ALERT = 'SYSTEM_ALERT';
}